### ISSUE TITLE
Criar página de vídeo

### ISSUE THREAD

**Issue by romulocollopy** [tmadeira/dolores#2]
a missão de dev é: criar uma página (hotsite) simples, com players dos vídeos.
essa é a página que as pessoas acessariam ao entrar no www.seacidadafossenossa.com.br

![photo_2016-04-28_16-25-01](https://cloud.githubusercontent.com/assets/1958236/14904568/e3263b36-0d5d-11e6-95ad-24a2684ac061.jpg)

**Comment by tmadeira** [comment]
Isso não é difícil de fazer. Basta criar uma página com esse template (algo como src/php/hotsite.php) e configurar o WordPress para usá-la como página inicial (em Administração -> Configurações -> Leitura -> A página inicial mostra).
